output_dir = "/flash/project_465002183/prime-rl/outputs/danish-alignment-lumi-multi-node"
max_steps = 1000
max_model_len = 4096
seq_len = 4096

[model]
name = "/flash/project_465002183/andreas/.cache/huggingface/hub/models--google--gemma-3-4b-it/snapshots/093f9f388b31de276ce2de164bdc2081324b9767"

[model.vlm]
vision_encoder_attr = "model.vision_tower"
language_model_attr = "model.language_model"

[deployment]
type = "multi_node"
gpus_per_node = 8
num_train_nodes = 1
num_infer_nodes = 1
num_judge_nodes = 1

[orchestrator]
batch_size = 128
rollouts_per_example = 8
use_token_client = false

[orchestrator.sampling]
max_tokens = 2048
temperature = 1.0

[[orchestrator.env]]
id = "fluent-alignment-da"
name = "danish-alignment"
args = { dataset_name = "V4ldeLund/no_robots_da_translated", dataset_split = "train", parse_fail_score = 3.0, judge_model_name = "mistralai/Mistral-Nemo-Instruct-2407", judge_base_url = "env:JUDGE_BASE_URL", judge_api_key_env = "DUMMY_API_KEY", judge_temperature = 0.2 }

[trainer.model]
attn = "sdpa"
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"

[trainer.model.ac]
freq = 1

[trainer.loss]
type = "default"
kl_tau = 1e-2

[trainer.tokenizer]
name = "/flash/project_465002183/andreas/.cache/huggingface/hub/models--google--gemma-3-4b-it/snapshots/093f9f388b31de276ce2de164bdc2081324b9767"

[trainer.optim]
lr = 1e-6

[ckpt]
interval = 100
keep_last = 10
keep_interval = 100

[inference]
gpu_memory_utilization = 0.85

[inference.parallel]
tp = 1
dp = 8

[judge_inference]
model.name = "google/gemma-3-27b-it"
gpu_memory_utilization = 0.9
server.port = 8001

[judge_inference.parallel]
tp = 1
dp = 8

[wandb]
offline = true
shared = false

[slurm]
job_name = "danish-alignment-lumi"
project_dir = "."
partition = "standard-g"
account = "project_465002183"
time = "24:00:00"
template_path = "src/prime_rl/templates/lumi/multi_node_rl.sbatch.j2"
