toml_files = ["../../examples/reverse_text/rl.toml"]

output_dir = "/flash/project_465002183/prime-rl/outputs/lumi-rl-single-node"
max_steps = 5

[deployment]
type = "single_node"
gpus_per_node = 8
num_train_gpus = 1
num_infer_gpus = 1

[trainer.model]
attn = "sdpa"

[orchestrator]
use_token_client = false

[wandb]
offline = true

[slurm]
job_name = "prime-rl-rl-lumi"
project_dir = "."
partition = "standard-g"
template_path = "src/prime_rl/templates/lumi/single_node_rl_lumi.sbatch.j2"
